// @ts-nocheck
/**
 * functionsCoverageReader.js
 *
 * Reads functions/coverage/coverage-final.json (generated by npm run test:coverage:functions).
 * Mirrors the structure of coverageReader.js so trust score + alerts can treat both uniformly.
 *
 * Run to generate: npm run test:coverage:functions
 */

'use strict';

const fs = require('fs');
const path = require('path');

const COVERAGE_PATH = path.join(__dirname, '../../../functions/coverage/coverage-final.json');

const STALE_WARN_MS = 24 * 60 * 60 * 1000;  // 24h
const STALE_CRIT_MS = 72 * 60 * 60 * 1000;  // 72h

// Conservative initial thresholds — ratchet up as coverage improves
const THRESHOLDS = { statements: 20, branches: 15, functions: 20, lines: 20 };

function pct(covered, total) {
    return total === 0 ? 100 : Math.round((covered / total) * 10000) / 100;
}

function getFunctionsCoverageSummary() {
    try {
        if (!fs.existsSync(COVERAGE_PATH)) {
            return {
                available: false,
                reason: 'No coverage data — run: npm run test:coverage:functions',
            };
        }

        const raw = JSON.parse(fs.readFileSync(COVERAGE_PATH, 'utf8'));
        const stat = fs.statSync(COVERAGE_PATH);

        let totalS = 0, covS = 0;
        let totalB = 0, covB = 0;
        let totalF = 0, covF = 0;
        let totalL = 0, covL = 0;

        for (const file of Object.values(raw)) {
            for (const v of Object.values(file.s || {})) { totalS++; if (v > 0) covS++; }
            for (const arr of Object.values(file.b || {})) {
                for (const v of arr) { totalB++; if (v > 0) covB++; }
            }
            for (const v of Object.values(file.f || {})) { totalF++; if (v > 0) covF++; }
            for (const v of Object.values(file.l || {})) { totalL++; if (v > 0) covL++; }
        }

        const statements = pct(covS, totalS);
        const branches   = pct(covB, totalB);
        const functions  = pct(covF, totalF);
        const lines      = pct(covL, totalL);
        const passing    = statements >= THRESHOLDS.statements &&
                           branches   >= THRESHOLDS.branches &&
                           functions  >= THRESHOLDS.functions &&
                           lines      >= THRESHOLDS.lines;

        return {
            available: true,
            generatedAt: stat.mtime.toISOString(),
            filesAnalyzed: Object.keys(raw).length,
            statements, branches, functions, lines,
            thresholds: THRESHOLDS,
            passing,
            status: passing ? 'passing' : 'below-threshold',
            coverage: {
                statements: { covered: covS, total: totalS, pct: statements },
                branches:   { covered: covB, total: totalB, pct: branches },
                functions:  { covered: covF, total: totalF, pct: functions },
                lines:      { covered: covL, total: totalL, pct: lines },
            },
        };
    } catch {
        return { available: false, reason: 'Failed to parse coverage-final.json' };
    }
}

/**
 * Generate alert objects for use in getProactiveAlerts().
 */
function getFunctionsCoverageAlerts(coverage, today) {
    const alerts = [];
    if (!coverage.available) {
        alerts.push({
            type: 'functions_coverage_missing',
            severity: 'warning',
            title: 'Functions Coverage Unavailable',
            description: '72 Cloud Function files — financial operations — have no coverage tracking',
            action: 'Run: npm run test:coverage:functions',
            source: 'Functions Coverage',
            date: today,
        });
        return alerts;
    }

    const ageMs = Date.now() - new Date(coverage.generatedAt).getTime();
    if (ageMs > STALE_CRIT_MS) {
        alerts.push({
            type: 'functions_coverage_stale',
            severity: 'warning',
            title: 'Functions Coverage Data Stale',
            description: `Coverage last generated ${Math.round(ageMs / 3600000)}h ago`,
            action: 'Run: npm run test:coverage:functions',
            source: 'Functions Coverage',
            date: today,
        });
    }

    if (!coverage.passing) {
        alerts.push({
            type: 'functions_coverage_below_threshold',
            severity: 'warning',
            title: 'Functions Coverage Below Threshold',
            description: `Statements: ${coverage.statements}% (threshold: ${coverage.thresholds.statements}%)`,
            action: 'Add tests for uncovered Cloud Function paths',
            source: 'Functions Coverage',
            date: today,
        });
    }

    return alerts;
}

module.exports = { getFunctionsCoverageSummary, getFunctionsCoverageAlerts };
