import type { CallableRegistryEntry } from '../callableRegistry';

export const bankRegistry: ReadonlyArray<CallableRegistryEntry> = [
    {
        name: 'linkBankAccount',
        version: 1,
        description: 'Link a bank account via Mono',
        trigger: 'callable',
        auth: 'required',
        rateLimit: null,
        status: 'stable',
        domain: 'bank',
    },
    {
        name: 'monoWebhook',
        version: 1,
        description: 'Mono bank webhook receiver',
        trigger: 'webhook',
        auth: 'none',
        rateLimit: null,
        status: 'stable',
        domain: 'bank',
    },
    {
        name: 'syncBankAccountNow',
        version: 1,
        description: 'Manually trigger bank account sync',
        trigger: 'callable',
        auth: 'required',
        rateLimit: null,
        status: 'stable',
        domain: 'bank',
    },
    {
        name: 'syncBankTransactions',
        version: 1,
        description: 'Scheduled bank transaction sync',
        trigger: 'scheduled',
        auth: 'none',
        rateLimit: null,
        status: 'stable',
        domain: 'bank',
    },
    {
        name: 'unlinkBankAccount',
        version: 1,
        description: 'Unlink a bank account',
        trigger: 'callable',
        auth: 'required',
        rateLimit: null,
        status: 'stable',
        domain: 'bank',
    },
];
