import type { CallableRegistryEntry } from '../callableRegistry';

export const familyRegistry: ReadonlyArray<CallableRegistryEntry> = [
    {
        name: 'acceptInvitation',
        version: 1,
        description: 'Accept a family connection invitation',
        trigger: 'callable',
        auth: 'required',
        rateLimit: 'invite',
        status: 'stable',
        domain: 'family',
    },
    {
        name: 'cleanupExpiredInvitations',
        version: 1,
        description: 'Scheduled cleanup of expired family invitations',
        trigger: 'scheduled',
        auth: 'none',
        rateLimit: null,
        status: 'stable',
        domain: 'family',
    },
    {
        name: 'confirmConnection',
        version: 1,
        description: 'Confirm a pending family connection',
        trigger: 'callable',
        auth: 'required',
        rateLimit: null,
        status: 'stable',
        domain: 'family',
    },
    {
        name: 'createFamilyInvitation',
        version: 1,
        description: 'Create a family connection invitation via email',
        trigger: 'callable',
        auth: 'required',
        rateLimit: 'createInvitation',
        status: 'stable',
        domain: 'family',
    },
    {
        name: 'disconnectFamily',
        version: 1,
        description: 'Remove or leave a family connection',
        trigger: 'callable',
        auth: 'required',
        rateLimit: 'disconnectFamily',
        status: 'stable',
        domain: 'family',
    },
    {
        name: 'getSharedAccountsWithMe',
        version: 1,
        description: 'List accounts shared with the current user',
        trigger: 'callable',
        auth: 'required',
        rateLimit: 'getSharedAccounts',
        status: 'stable',
        domain: 'family',
    },
    {
        name: 'migrateFamilyConnectionsV2',
        version: 1,
        description: 'One-time V1→V2 family connection migration',
        trigger: 'callable',
        auth: 'required',
        rateLimit: 'familyMigration',
        status: 'deprecated',
        domain: 'family',
        deprecationNotice: 'Use runMigration with id "001" instead',
        replacedBy: 'runMigration',
    },
    {
        name: 'onSharedTransactionWrite',
        version: 1,
        description: 'Trigger: sync notifications on shared transaction write',
        trigger: 'trigger',
        auth: 'none',
        rateLimit: null,
        status: 'stable',
        domain: 'family',
    },
    {
        name: 'revokeInvitation',
        version: 1,
        description: 'Revoke a pending family invitation',
        trigger: 'callable',
        auth: 'required',
        rateLimit: 'revokeInvitation',
        status: 'stable',
        domain: 'family',
    },
    {
        name: 'shareAccount',
        version: 1,
        description: 'Share or unshare a financial account with family',
        trigger: 'callable',
        auth: 'required',
        rateLimit: 'shareAccount',
        status: 'stable',
        domain: 'family',
    },
    {
        name: 'validateInvitationToken',
        version: 1,
        description: 'Validate a family invitation token',
        trigger: 'callable',
        auth: 'required',
        rateLimit: 'tokenValidation',
        status: 'stable',
        domain: 'family',
    },
];
