import type { CallableRegistryEntry } from '../callableRegistry';

export const financeRegistry: ReadonlyArray<CallableRegistryEntry> = [
    {
        name: 'addTransactionToSharedAccount',
        version: 1,
        description: 'Add a transaction to a shared account',
        trigger: 'callable',
        auth: 'required',
        rateLimit: 'transactionCreate',
        status: 'stable',
        domain: 'finance',
    },
    {
        name: 'createRecurringTransaction',
        version: 1,
        description: 'Create a recurring transaction rule',
        trigger: 'callable',
        auth: 'required',
        rateLimit: 'transactionCreate',
        status: 'stable',
        domain: 'finance',
    },
    {
        name: 'deleteRecurringTransaction',
        version: 1,
        description: 'Delete a recurring transaction rule',
        trigger: 'callable',
        auth: 'required',
        rateLimit: null,
        status: 'stable',
        domain: 'finance',
    },
    {
        name: 'fixSharedAccountScopes',
        version: 1,
        description: 'Fix scope field on shared account transactions',
        trigger: 'callable',
        auth: 'required',
        rateLimit: null,
        status: 'internal',
        domain: 'finance',
    },
    {
        name: 'processRecurringTransactions',
        version: 1,
        description: 'Scheduled processing of due recurring transactions',
        trigger: 'scheduled',
        auth: 'none',
        rateLimit: null,
        status: 'stable',
        domain: 'finance',
    },
    {
        name: 'toggleRecurringTransaction',
        version: 1,
        description: 'Enable or disable a recurring transaction rule',
        trigger: 'callable',
        auth: 'required',
        rateLimit: null,
        status: 'stable',
        domain: 'finance',
    },
    {
        name: 'updateRecurringTransaction',
        version: 1,
        description: 'Update a recurring transaction rule',
        trigger: 'callable',
        auth: 'required',
        rateLimit: null,
        status: 'stable',
        domain: 'finance',
    },
];
