import type { CallableRegistryEntry } from '../callableRegistry';

export const infraRegistry: ReadonlyArray<CallableRegistryEntry> = [
    // ── Infrastructure ───────────────────────────
    {
        name: 'checkRateLimit',
        version: 1,
        description: 'Check rate limit status for a bucket',
        trigger: 'callable',
        auth: 'required',
        rateLimit: null,
        status: 'internal',
        domain: 'infra',
    },
    {
        name: 'health',
        version: 1,
        description: 'Health check endpoint',
        trigger: 'callable',
        auth: 'none',
        rateLimit: null,
        status: 'stable',
        domain: 'infra',
    },
    {
        name: 'logAuditEvent',
        version: 1,
        description: 'Log a security/audit event',
        trigger: 'callable',
        auth: 'required',
        rateLimit: null,
        status: 'stable',
        domain: 'infra',
    },
    {
        name: 'resetRateLimit',
        version: 1,
        description: 'Reset a rate limit bucket (admin)',
        trigger: 'callable',
        auth: 'required',
        rateLimit: null,
        status: 'internal',
        domain: 'infra',
    },

    // ── Migration Framework ──────────────────────
    {
        name: 'getMigrationStatus',
        version: 1,
        description: 'Get status of a specific migration',
        trigger: 'callable',
        auth: 'required',
        rateLimit: null,
        status: 'stable',
        domain: 'migration',
    },
    {
        name: 'listMigrations',
        version: 1,
        description: 'List all registered migrations with metadata',
        trigger: 'callable',
        auth: 'required',
        rateLimit: null,
        status: 'stable',
        domain: 'migration',
    },
    {
        name: 'rollbackMigration',
        version: 1,
        description: 'Rollback a previously completed migration',
        trigger: 'callable',
        auth: 'required',
        rateLimit: 'familyMigration',
        status: 'stable',
        domain: 'migration',
    },
    {
        name: 'runMigration',
        version: 1,
        description: 'Run a migration (with optional dry-run)',
        trigger: 'callable',
        auth: 'required',
        rateLimit: 'familyMigration',
        status: 'stable',
        domain: 'migration',
    },

    // ── User Account ─────────────────────────────
    {
        name: 'deleteMyAccount',
        version: 1,
        description: 'Permanently delete user account and all associated data',
        trigger: 'callable',
        auth: 'required',
        rateLimit: 'deleteAccount',
        status: 'stable',
        domain: 'user',
    },
    {
        name: 'submitFeedback',
        version: 1,
        description: 'Submit user feedback or bug report',
        trigger: 'callable',
        auth: 'required',
        rateLimit: null,
        status: 'stable',
        domain: 'user',
    },
];
