import type { CallableRegistryEntry } from '../callableRegistry';

export const notificationsRegistry: ReadonlyArray<CallableRegistryEntry> = [
    {
        name: 'dismissNotification',
        version: 1,
        description: 'Dismiss a notification',
        trigger: 'callable',
        auth: 'required',
        rateLimit: 'dismissNotification',
        status: 'stable',
        domain: 'notifications',
    },
    {
        name: 'getNotifications',
        version: 1,
        description: 'Fetch notifications with optional filters',
        trigger: 'callable',
        auth: 'required',
        rateLimit: 'getNotifications',
        status: 'stable',
        domain: 'notifications',
    },
    {
        name: 'processBillReminders',
        version: 1,
        description: 'Scheduled processing of bill reminder notifications',
        trigger: 'scheduled',
        auth: 'none',
        rateLimit: null,
        status: 'stable',
        domain: 'notifications',
    },
    {
        name: 'processReminders',
        version: 1,
        description: 'Scheduled processing of push notification reminders',
        trigger: 'scheduled',
        auth: 'none',
        rateLimit: null,
        status: 'stable',
        domain: 'notifications',
    },
    {
        name: 'sendTemplatedEmail',
        version: 1,
        description: 'Send a templated email notification',
        trigger: 'callable',
        auth: 'required',
        rateLimit: 'emailSend',
        status: 'internal',
        domain: 'notifications',
    },
];
