// @ts-nocheck
'use strict';

const router = require('express').Router();
const fs = require('fs');
const path = require('path');
const gitData = require('../gitDataProvider');
const { findPotentialDuplicate } = require('../helpers/dedup');

/**
 * POST /api/webhooks/sentry
 * Receives Sentry webhooks and creates matching BUG tickets in the PM Dashboard.
 */
router.post('/api/webhooks/sentry', async (req, res) => {
    try {
        const payload = req.body;

        // Sentry webhook payloads differ depending on the trigger.
        // Typically, new issues are found in payload.data.issue
        const issue = payload?.data?.issue || payload;

        if (!issue || !issue.title) {
            return res.status(400).json({ error: 'Invalid Sentry payload: Missing issue title' });
        }

        const project = issue.project?.name || 'anchor-os';
        const environment = issue.environment || 'production';
        const culprit = issue.culprit || 'Unknown Culprit';
        const url = issue.url || issue.web_url || '';

        // Format into an Anchor OS ticket shape
        const title = `[Sentry] ${issue.title}`;
        const description = `Sentry identified a new runtime error in **${environment}**.\n\n` +
            `**Project:** ${project}\n` +
            `**Culprit:** ${culprit}\n` +
            `**Sentry URL:** ${url}\n\n` +
            `*This ticket was automatically generated by the Sentry Webhook pipeline.*`;

        const roadmapPath = path.join(__dirname, '../roadmap.json');

        // Ensure roadmap file exists before reading
        if (!fs.existsSync(roadmapPath)) {
            return res.status(404).json({ error: 'System roadmap.json not found' });
        }

        const roadmapData = JSON.parse(fs.readFileSync(roadmapPath, 'utf8'));

        // Prevent opening 50 tickets for the same crash
        const duplicate = findPotentialDuplicate(roadmapData.initiatives || [], title, description);
        if (duplicate) {
            console.log(`[Sentry Webhook] Ignored duplicate issue: ${title} matches ${duplicate.id}`);
            return res.status(200).json({
                message: 'Ignored as duplicate',
                duplicate
            });
        }

        // Get a new BUG ID
        const newId = await gitData.getNextId('BUG');

        const newInitiative = {
            id: newId,
            team: 'Engineering',
            priority: 'P1',  // Sentry crashes default to P1
            title: title,
            description: description,
            status: 'planned',
            detectionPatterns: [newId],
            effort: 'medium',
            impact: 'high',
            createdAt: new Date().toISOString().split('T')[0]
        };

        // Save to roadmap
        roadmapData.initiatives.unshift(newInitiative);
        roadmapData.lastUpdated = new Date().toISOString().split('T')[0];
        fs.writeFileSync(roadmapPath, JSON.stringify(roadmapData, null, 4));

        console.log(`[Sentry Webhook] Successfully created ticket ${newId} for: ${title}`);

        return res.status(201).json({
            success: true,
            message: `Created ${newId}`,
            ticket: newInitiative
        });

    } catch (error) {
        console.error('[Sentry Webhook Error]', error);
        return res.status(500).json({ error: error.message });
    }
});

module.exports = router;
